<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>List Product</title>
    <base href="http://localhost/zend2112/public/">
</head>
<style>
.my-message ul li{
    list-style-type:none;

}
</style>
<body>

    <div class="row">
        <div class="col-sm-4 col-sm-offset-4 my-message">
            <?= $this->flashMessenger()->render('success',['alert','alert-success']);?>
            <?= $this->flashMessenger()->render('warning',['alert','alert-warning']);?>
        </div>
    </div>
    <h2>
        <div style="float:l,eft;width:80%">List of products</div>
        <div style="float:right;width:20%;text-align:right">
        <a href="<?=$this->url('products',[
            'controller'=>'product',
            'action'=>'add'
        ])?>">Add</a>
        </div>
    </h2>

    <table class="table table-hover">
        <thead>
            <th>STT</th>
            <th>Name</th>
            <th>Name Type</th>
            <th>Summary</th>
            <th>Price</th>
            <th>Image</th>
            <th>Options</th>
        </thead>
        <tbody>
            <?php 
            $stt = 1;
            foreach($this->products as $p):
            $p = (object)$p;
            ?>

            <tr>
                <td><?=$stt++?></td>
                <td><?=$p->name?></td>
                <td><?=$p->name_type?></td>
                <td><?=$p->summary?></td>
                <td><?=number_format($p->price)?></td>
                <td width="30%">
                <?php
                    $images = json_decode($p->image);
                    foreach($images as $img):?>
                    <img src='img/images/<?=$img?>' height="80px">
                <?php endforeach ?>
                </td>
                <td>
                <a  href="<?=$this->url('products',[
                    'controller'=>'product',
                    'action'=>'edit',
                    'page'=>$p->id
                ])?>">Edit</a> | 
                <a  href="<?=$this->url('products',[
                    'controller'=>'product',
                    'action'=>'delete',
                    'page'=>$p->id
                ])?>">Delete</a></td>
            </tr>
            <?php endforeach?>
            
        </tbody>
    </table>
    <div class="row">
                <?= $this->paginationControl(
                $products,
                'Sliding',
                'paginator/pagination-2.phtml',
                ['route' => 'products']
            ) ?>
    </div>

</body>

</html>