<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>List News</title>
    <base href="http://localhost:8080/zendnews/public/">
    
</head>

<style>
    	.my-message ul li{
    		list-style-type:none;

		}
		.table {
			margin-top: 20px;
		}
</style>

<body>

	<h2 class="text-center">Tin tức đã xóa</h2>
	<br>
	<a href="<?=$this->url('news',[
		'controller'=>'news',
		'action'	=>'index'
	])?>" class="btn btn-primary" id="add">Trang chủ</a>
	
	<table class="table table-hover" id="table">
		<thead>
			<th>idbv</th>
			<th>Tiêu đề</th>
			<th>Ngày</th>
			<th>Tên loại</th>
			<th>urlHinh</th>
			<th>Tùy chỉnh</th>
		</thead>
		<tbody>
			<?php
				foreach($this->result as $p):
				$p = (object)$p;
			?>
			<tr id="news">
				<td><?=$p->idbv ?></td>
				<td><?=$p->TieuDe ?></td>
				<td><?=$p->Ngay ?></td>
				<td><?=$p->loai ?></td>
				<td width="30%">
               
                <?php
                    $images = json_decode($p->urlHinh);
                    foreach($images as $img):?>
                    <img src='img/images/<?=$img?>' height="80px">
                <?php endforeach ?>

                </td>

                <td>
                	<a href="<?=$this->url('news',[
                		'controller'=>'news',
                		'action'	=>'backup',
                		'page'=>$p->idbv
                	])?>">Khôi phục</a>
                </td>
			</tr>
			
			<?php
				endforeach;
			?>
		</tbody>
	</table>

	<div class="row">
		<?=
			$this->paginationControl(
    		$result,
    		'Sliding',
    		'paginator/pagination_del.phtml',
    		['route' => 'news']
		) ?>
	</div>

	
</body>
</html>