<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Delete</title>
</head>
<body>
    <h2>Bạn có muốn xóa bài viết <i>"<?=$news->TieuDe?>"</i></h2>
    <form action="<?=$this->url('news',[
        'controller'=>'news',
        'action'=>'delete',
        'page'=>$news->idbv
    ])?>" method="post">

        <input type="hidden" name="idbv" value="<?=(int)$news->idbv ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />

    </form>
</body>
</html>