<?php
$form = $this->form;
$form->setAttributes([
	'enctype' => 'multipart/form-data',
	'class'=>'form-horizontal',
	'action'=>$this->url('news',[
		'controller'=>'news',
		'action'	=>'edit',
		'page'		=>$news->idbv
	]),
	
]);

$tieude = $form->get('TieuDe');
$lang 	= $form->get('lang');
$tomtat	= $form->get('TomTat');
$urlhinh= $form->get('urlHinh');
$content= $form->get('Content');
$idloai = $form->get('idLoai');
$noibat = $form->get('NoiBat');
$btn	= $form->get('btnSubmit');

$form->prepare();
?>
<script src="../ckeditor/ckeditor.js"></script>
<div class="row">
	<div class="col-sm-12">
		<h2>Thêm bài viết mới</h2>
		<?=$this->form()->openTag($form)?>
			
			<div class="form-group">
				<?=$this->formLabel($tieude)?>
				<div class="col-sm-10">
					<?php
						echo $this->formElement($tieude);
						echo $this->formElementErrors($tieude);
					?>	
				</div>
			</div>

			<div class="form-group">
				<?=$this->formLabel($lang)?>
				<div class="col-sm-10">
					<?php
						echo $this->formElement($lang);

					?>	
				</div>
			</div>
			
			<div class="form-group">
				<?=$this->formLabel($tomtat)?>
				<div class="col-sm-10">
					<?php
						echo $this->formElement($tomtat);
						echo $this->formElementErrors($tomtat);
					?>	
				</div>
			</div>

			<div class="form-group">
				<?=$this->formLabel($urlhinh)?>
				<div class="col-sm-2">
					<?php
						echo $this->formElement($urlhinh);
						echo $this->formElementErrors($urlhinh);
					?>	
				</div>

				<div class="col-sm-8">
					<?php 
						$images = json_decode($news->urlHinh);
						foreach($images as $img):
					?>
					<img src="../../img/images/<?=$img?>" height=70px>
				<?php endforeach ?>
				</div>
			</div>

			<div class="form-group">
				<?=$this->formLabel($content)?>
				<div class="col-sm-10">
					<?php
						echo $this->formElement($content);
						echo $this->formElementErrors($content);
					?>	
				</div>
					<script>
                		CKEDITOR.replace('content')
                	</script>
			</div>

			<div class="form-group">
				<?=$this->formLabel($idloai)?>
				<div class="col-sm-10">
					<?php
						echo $this->formElement($idloai);
					?>	
				</div>
			</div>


			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<div class="checkbox">
						<label>
							<?php
								echo $this->formElement($noibat);
							?>	
							Nổi bật
						</label>
					</div>
					
				</div>
			</div>

			<div class="form-group">
            	<div class="col-sm-offset-2 col-sm-10">
                	<?=$this->formElement($btn);?>
            	</div>
        	</div>


		<?=$this->form()->closeTag()?>
	
	</div>
</div>