<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>List News</title>
    <base href="http://localhost/zendnews/public/">
</head>
<body>
	<table class="table table-hover">
		<thead>
			<th>idbv</th>
			<th>Tiêu đề</th>
			<th>Ngày</th>
			<th>Tên loại</th>
			<th>urlHinh</th>
		</thead>
		<tbody>
			<?php
				foreach($this->result as $p):
				$p = (object)$p;
			?>
			<tr>
				<td><?=$p->idbv ?></td>
				<td><?=$p->TieuDe ?></td>
				<td><?=$p->Ngay ?></td>
				<td><?=$p->loai ?></td>
				<td width="30%">
                <?php
                    $images = json_decode($p->urlHinh);
                    foreach($images as $img):?>
                    <img src='http://localhost/zendnews/public/img/images/<?=$img?>' height="80px">
                <?php endforeach ?>

                </td>
			</tr>
			
			<?php
				endforeach;
			?>
		</tbody>
	</table>

	<div class="row">
		<?php 
			$this->paginationControl(
    		$result,
    		'Sliding',
    		'paginator/pagination.phtml',
    		['route' => 'news']
		) ?>
	</div>
</body>
</html>