

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>List News</title>
    <base href="http://localhost/zendnews/public/">
    
</head>

<style>
    	.my-message ul li{
    		list-style-type:none;

		}
		.table {
			margin-top: 20px;
		}
		h2{
			color: #f97923;
			font-weight: bold;
		}
</style>

<body>
	<div class="row">
        <div class="col-sm-4 col-sm-offset-4 my-message">
            <?= $this->flashMessenger()->render('success',['alert','alert-success']);?>
            <?= $this->flashMessenger()->render('warning',['alert','alert-warning']);?>
        </div>
    </div>
	
	<h2 class="text-center">Danh sách tin tức</h2>
	<br>
	<a href="<?=$this->url('news',[
		'controller'=>'news',
		'action'	=>'add'
	])?>" class="btn btn-primary" id="add">Thêm tin mới</a>
	
	<a href="<?=$this->url('news',[
		'controller'=>'news',
		'action'	=>'deletedList'
	])?>" class="btn btn-danger" id="add">Tin đã xóa</a>
	
	<a href="<?=$this->url('news',[
		'controller'=>'news',
		'action'	=>'hotNews'
	])?>" class="btn btn-success" id="add">Tin nổi bật</a>
	
	
	
	<table class="table table-hover" id="table">
		<thead>
			<th>idbv</th>
			<th>Tiêu đề</th>
			<th>Ngày</th>
			<th>Tên loại</th>
			<th>urlHinh</th>
			<th>Tùy chỉnh</th>
		</thead>
		<tbody>
			<?php
				foreach($this->result as $p):
				$p = (object)$p;
			?>
			<tr id="news">
				<td><?=$p->idbv ?></td>
				<td><?=$p->TieuDe ?></td>
				<td><?=$p->Ngay ?></td>
				<td><?=$p->loai ?></td>
				<td width="30%">
               
                <?php
                    $images = json_decode($p->urlHinh);
                    foreach($images as $img):?>
                    <img src='img/images/<?=$img?>' height="80px">
                <?php endforeach ?>

                </td>

                <td>
                	<a href="<?=$this->url('news',[
                		'controller'=>'news',
                		'action'	=>'edit',
                		'page'=>$p->idbv
                	])?>">Sửa</a> | 

                	<a href="<?=$this->url('news',[
                		'controller'=>'news',
                		'action'	=>'delete',
                		'page'=>$p->idbv
                	])?>">Xóa</a>
                </td>
			</tr>
			
			<?php
				endforeach;
			?>
		</tbody>
	</table>

	<div class="row">
		<?=
			$this->paginationControl(
    		$result,
    		'Sliding',
    		'paginator/pagination.phtml',
    		['route' => 'news']
		) ?>
	</div>

	
</body>
</html>