<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title></title>
</head>
<body>
	<table class="table table-hover">
		<thead>
			<th>idbv</th>
			<th>Tiêu đề</th>
			<th>Ngày</th>
			<th>Tên loại</th>
			<th>urlHinh</th>
		</thead>
		<tbody>
			<?php
				foreach($this->result as $p):
				$p = (object)$p;
			?>
			<tr>
				<td><?=$p->idbv ?></td>
				<td><?=$p->TieuDe ?></td>
				<td><?=$p->Ngay ?></td>
				<td><?=$p->loai ?></td>
				<td width="30%">
                <?php
                    $images = json_decode($p->urlHinh);
                    foreach($images as $img):?>
                    <img src='http://localhost/zendnews/public/img/images/<?=$img?>' height="80px">
                <?php endforeach ?>

                </td>
			</tr>
			
			<?php
				endforeach;
			?>
		</tbody>
	</table>
</body>
</html>