<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("p").click(function(){
        $(this).hide();
    });
});
</script>
</head>
<body>

<p>If you click on me, I will disappear.</p>
<p>Click me away!</p>
<p>Click me too!</p>

</body>
</html>
<div id="myModal" class="modal fade" role="dialog">
	  <div class="modal-dialog modal-sm">

	    <!-- Modal content-->
	    <div class="modal-content">
	    
	      <div class="modal-body">
	        <p>Bạn có chắc chắn xoá bài viết <b class="name-news">..</b> </p>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-success" id="btnOk">OK</button>
	        <button type="button" class="btn btn-default" id="btnCancel" data-dismiss="modal">Cancel</button>
	      </div>
	    </div>

	  </div>
	</div>

	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<script>
	$(document).ready(function(){
		
		$('.delete').click(function(){
			$('.modal-body').html('<p>Bạn có chắc chắn xoá bài viết <b class="name-news">..</b> </p>')
			$('#btnOk').show()
			$('#btnCancel').html("Cancel")



			var id = $(this).attr('data-id')
			var name = $(this).attr('data-name')
			$('.name-news').html(name)
			$('#myModal').modal('show')

			

			$('#btnOk').click(function(){
				var url =  "<?=$this->url('news',[
					'controller'=>'news',
					'action'	=>'delete',
					'page'=>$result->idbv
				])?>"

					$.ajax({
						url:url,
						type:"GET",
						success:function(res){
		                    if(res.result =='success'){
		                        $('.modal-body').html('Xoá thành công')
		                        $('#news-'+id).hide()
		                    }
		                    else{
		                        $('.modal-body').html('Xoá không thành công')
		                    }
		                    $('#btnOk').hide()
		                    $('#btnCancel').html('OK')
                }

				})
			})
			
		});
}
	</script>